name: MMOCore
version: '1.0.1'
main: net.hyperion.mMOCore.MMOCore
api-version: '1.21'
depend: []
softdepend: []

commands:
  mmocore:
    description: Main MMOCore command
    usage: /<command> [check|reload|help]
    permission: mmocore.use
  attribute:
    description: Manage attribute points
    usage: /<command> spend <attribute> <amount>
    permission: mmocore.use

permissions:
  mmocore.use:
    description: Basic MMOCore usage
    default: true
  mmocore.admin.reload:
    description: Reload MMOCore configuration
    default: op
